# Generated by Django 6.0.1 on 2026-01-26 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='dep_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.departments'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='p_email',
            field=models.EmailField(max_length=254),
        ),
    ]
