# Generated by Django 6.0.1 on 2026-03-15 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_booking_dep_name_alter_booking_p_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=255)),
                ('c_email', models.EmailField(max_length=255)),
                ('c_sub', models.CharField()),
                ('c_msg', models.TextField()),
                ('submited_on', models.DateField(auto_now=True)),
            ],
        ),
    ]
